version: '3.8'

services:
  myappservice:
    image: my-java-app:1.3
    container_name : userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres12:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword


    depends_on:
      - postgres
    ports:
      - "8081:8081"

    networks:
      - bridge_network

  postgres:
    image: postgres:12
    container_name: postgres12
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
#      TZ: UTC   # Works fine in Postgres 12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bridge_network

volumes:
  pgdata:
networks:
  bridge_network :
    driver: bridge
